[tool.pyright]
venvPath = "."
venv = ".venv"

[project]
name = "spacesaver-transcode"
version = "v0.1.0"
description = "---"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["app/src"]
namespaces = true
