apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spacesaver-transcode
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`transcode.spacesaver.lan`)
      kind: Rule
      services:
        - name: spacesaver
          port: 8000
